version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giothanhle-client
    command: yarn dev
    ports:
      - '80:3000'
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    restart: unless-stopped

networks:
  default:
    driver: bridge