version: '3.8'

services:
  giole-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: giole-app
    command: "sh /app/docker-entrypoint.sh"
    restart: always
    ports:
      - '2000:3000'
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules