version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: giole-app
    restart: always
    ports:
      - '80:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules