version: "3.8"

services:
  giole-app-production:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: giole-app-production
    restart: always
    ports:
      - ${APP_PORT}:3000
