version: "3.8"

services:
  giole-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: giole-app-dev
    command: "sh /app/docker-entrypoint.sh"
    restart: no
    ports:
      - "2000:3000"
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
