name: Giole.com.vn CD

on:
  workflow_run:
    workflows: ["build"]
    types:
      - success

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/giole.com.vn
            git pull origin production
            git status
            make production
