name: Deploy

on:
  pull_request:
    types: [closed]
    branches: [production]

jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.merged == true }}
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/giole.com.vn
            git pull origin production
            git status
            make production
