name: Build

on:
  pull_request:
    branches: [production]
  push:
    branches: [production]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Build and test
        run: |
          touch .env
          echo NEXT_PUBLIC_API_URI=${{ secrets.NEXT_PUBLIC_API_URI }} >> .env
          cat .env
          docker build -t giole-container .
          docker run giole-container yarn lint
